language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests tests.unit
deploy:
  provider: pypi
  on:
    tags: true
  password:
    secure: fW+0EX5yS48f7r4tJMdFck7Mq4SRds9GsngkzV0iu5wLGzjrpnuKo1v1MVdq9Wy9KZqGWFBLduWbCZoes6eiSQ9j+5d7A3F5r7oYr74mlXeTvapouBMVbXX8ZGuPZXxN7gvkrLQIt6p01PhNPGvtzWJ68OerLdlFvNs127EJ4FiO0lAQsPpjjBTt95ZeZlqjzc5j2Ub8nNXtAgv+G+oeZZiW37VkGDga0EVFzSX0uvcTDBxjvjsqs7Td7GoT9p3G6TQMKPtJz2pKCh/2kJywMtgkcC+9PiG/Mux/K3AIUGPQc5o5HxkR8UEHftMP+uVgjscytTl8c5b8vaxXCckUTQ06s6eVJbuNk7lbc3LHsTXvQ19l0j8B0cbutkiGHvOFq7VNSygNoU6jjBAI6zKnvKh8Ecx34TncCGabDVfPhLqVB7hq7nb154gFpCSYULx9qz1+9pV0MsVGYkdhF5kPk1xRR9xkp/w4LpXq0fSVlIRnt3xr9a4v7f+08hNvM+vU2HSeKLo447U8gweP7CPAb8NjQ+BhTjiBnsB45QJvNvihgppwEeGLM5WsRyGKU6YVIj/pYehkvjTysHSTFys9fVbEzUgU1fXkAj89mNbBLstHP479iD/WTcYKCZ/WhVOme7xRa09JVvGRnQlg9rXYi2El5mn41ma7K13ecz3gIF0=
  user:
    secure: MYOU8xq5AfI5IiLAa71l4NNnB2ffdqP45S0tmAb3gykGnPEVGGq64BeXNsZjHOC6okxs2WXyGINWiPjK8uc1HlAu/0ZK1A/8LdzAQjUUHMUZ7k9bFqtN9+N+OgF7r9lQBILOkRw6XKh23/THucAIEyTsoX6bn/N3t0U1rn1YXizQX0gDEh0fvjz9++Aun3Y9Agtn0A9nAJZI38RpPAuYvAh1bKtrZoZ1HjmaGbwOGTe77R7B8VdWmti5TNUv3ilcVS3GCFfisJDYJJQ/hp/V/vRMZjFWQeN5rMylM6Wk/X5ktqWFDu+tlgd8Z1lGK2LMkca+Bb1kAO/vHC8tHuZK+i40/yei7K0EWO7zRB5/ezdue/sY6wXAcGVi43jQA/bhTUmipmPq/I9rEaM7IED1NNKDFmQFd4xnGQ4ff9q375lsYfnrAI3uw2UjKmclBjhfR8iAsId2rlC+v2w5FAOJyJvAWjDTsR4bnSf3uWqFOTQlLQp/ozLE8rUjpouF2v4AAGNMbpvLYt1c2vPTbU288RaehQORmAw1sjbYLOReMOvBUtKWbB3eHzSVMpY8GoiOVoL+uT7CIguOFYG+n6ZytyERMH9jlC0oOooBA1Blus98OWpCMlVcqcD78CReg4n+wrcLe4EWwxFBg78dm2R/O1XZ5pc7cctHm9+jDqtdsTQ=
notifications:
  hipchat:
    rooms:
      secure: bVVtCHBpdn11Yv/dqdve0AO2Y/VaVqQTCP17G6WGo42rDW9qzQZAEe6T72XVwp67ax2chRW9UQXoqR9J99CNgiKTjYyGMCMJhPyb/tkUPbrf4WpVhDRTflvT5v/+nzKfOg0jO2qSpl+bvZU+g4XNbAJHBtOm5NG1jKFWx92lW7HNluE+3osrcmWhVAjiBsVH1sjUJCRa5EuDncSwrZy99wQoa+J5aj3JqDb7lpI2kD7H2ug3VXqcdFXVa7BscWHUZMstSq5O9/wa3JzZMZeCztj0aGRKsXPzCOeh0iuVndXd5nt+e2xcrYRbwMROUOpPmfSxQ8+fD15b0QH07rKE6zxqPF1pWCTzjQx9VDKDXkJ2w+r0D126YOXgVLCe7jPacoPM+oj/MUPg8jGf14DB8W57zMFhzCIW7Q9m2s2BO77HsTlZBz24FeZV9cA9rbzcJoX8Nhz37UfR0QFx7or/KE9jHs6DiErbUh8XGuZ4dS+bCevrjyvgDHqFZZkrvZ+D/R1M6xs9o2cNstTkKbxGDkOm7l3Sapm5Nf8B8IWUbL4k5za72SO7vmYXC0pLo4EPNeirjEUkHGJ7bO8CWygJHOAgMYSgR/3fcNhJ3qG7yy73Bth0brQWwIeLv1T+QjCdKvLqochsAEnqA/srqSozjccoNzRYiVoisUSTsQxXoAw=
